### PR TITLE
Project: Associations

### PR DESCRIPTION
**Pull request by srizzuto**
We build a site similar to a private Eventbrite which allows users to create events and then manage user signups. Users can create events and send invitations and parties. Events take place at a specific date and at a location (which you can just store as a string, like “Andy’s House”).

-Implemented Authentication with Devise
-Added Bootstrap for styling

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS:CHANGES REQUIRED** :recycle: :recycle: :construction: :construction_worker: 

Good job on this project. Congratulations on the extra effort you've put in for authenticating users. :+1: :clap: 

Please see below required changes.

- [x] Always adopt the correct git flow. Main, development(default), and feature branch. Pull request from the feature branch to the default branch.

**App Behaviour**
- [x] There's a bug in the event's show page. A single user could be invited multiple times to the same event. Please correct it.  
- [x] There's no navigation link to the user show page. Please add a clickable link that leads to a user's show page without having to manually edit the url.
- [x] The user's show page should display events the user has created and events that the user is attending to separated in past and upcoming.

**Controllers**

User's show action should do the following:

- [x] List events created by user, i.e. @created_events = current_user.events.
- [x] List events previously attended by user using event model scope, i.e. @past_events = current_user.attended_events.previous.
- [x] List upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming.

**Tests**

- [x] Models must have unit tests for validations and associations (use Rspec).
- [x] Authentication has integration tests (use Rspec + Capybara).
- [x] Event management features have integration tests (Rspec + Capybara).

[OPTIONAL]

- [x] There should be absolutely no logic in your view. Make use of helper methods. Please check your event's show.html file.

Please implement the necessary changes and submit another CRR once you're ready.

Feel free to drop your message here if you require  help and/or clarification.

Cheers and happy coding. :smile:

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- The user's show page that display events the user has created and events that the user is attending to separated in past and upcoming. :+1: 
- There's navigation link to the user show page. :100: 

To improve :factory_worker: [REQUIRED]:

- [x] Please add more test units. The aim is to ensure that your APP works correctly. Don't forget to use Capybara ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

Nice to have [OPTIONAL] :

- [ ] an index for creator_id column is added
- [ ] an index for event_id column is added
- [ ] an index for attendee_id column is added
- [ ] There should be absolutely no logic in your view. Make use of helper methods. Please check your event's show.html file.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Changes Required :recycle:
### Hello team, 
**You have a great job on this job and it is almost ready for approval
However, there are testing requirements that have not been met :clap:**
## To improve
- [ ] Since this project mainly focuses on associations, it is important that your tests cover the associations as well. Kindly Add tests for the associations as suggested by @george-shammar.

## Optional
- [ ] It would be better to implement the optional changes suggested by @rindrajosia.

**Please make the above changes and ask for another review**

Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply.

### Happy Coding

_Slack: Oloo Moses_

**Comment by srizzuto** [comment]
Hello, @oloomoses .

We have implemented test associations while creating events and attendees from the models. You couldn't find them?

**Comment by oloomoses** [comment]
Thanks for reaching out. A very easy way of testing associations is with [shoulda](https://github.com/thoughtbot/shoulda).
Kindly check it out and I hope you find this helpful.

**Comment by barackm** [comment]
The requested change was already implemented, so the previous reviewer said that we can consider it as just optional
this is his message: 
> The project is well done and ready for approval. Kindly consider the requirement as optional. But it would be great if you work on it.

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professinal. 💯 
  - Feedback implemented. 💯 

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
